/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Funcionario;

import Vista.CambiaPanel;
import Vista.login;
import Vista.modDataPane;
import Vista.usuarioHome;
import Vista.gestReservasPane;

/**
 *
 * @author ander
 */
public class funPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form funPrincipal
     */
    public int codUsuaraio;
    
    public funPrincipal(int codUsuario) {
        this.codUsuaraio = codUsuario;
        initComponents();
        this.setLocationRelativeTo(null);
       
       new CambiaPanel(PrincipalPane, new usuarioHome(codUsuario));
    }
    
    public int cod(){
        return codUsuaraio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PeneContent = new javax.swing.JPanel();
        PrincipalPane = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        Desplegable = new javax.swing.JPanel();
        modData = new Vista.recurso.RSButtonMetro();
        gestRes = new Vista.recurso.RSButtonMetro();
        vigHouse = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PeneContent.setBackground(new java.awt.Color(255, 255, 255));
        PeneContent.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        PrincipalPane.setBackground(new java.awt.Color(255, 255, 255));
        PrincipalPane.setPreferredSize(new java.awt.Dimension(704, 400));
        PrincipalPane.setLayout(new javax.swing.BoxLayout(PrincipalPane, javax.swing.BoxLayout.LINE_AXIS));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(230, 0, 0));
        cerrar.setText(" X ");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        Desplegable.setBackground(new java.awt.Color(255, 0, 0));

        modData.setText("Modificar Datos");
        modData.setColorHover(new java.awt.Color(255, 255, 255));
        modData.setColorNormal(new java.awt.Color(255, 0, 0));
        modData.setColorPressed(new java.awt.Color(222, 4, 4));
        modData.setColorTextHover(new java.awt.Color(255, 0, 0));
        modData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modDataActionPerformed(evt);
            }
        });

        gestRes.setText("Gestionar Reserva");
        gestRes.setColorHover(new java.awt.Color(255, 255, 255));
        gestRes.setColorNormal(new java.awt.Color(255, 0, 0));
        gestRes.setColorPressed(new java.awt.Color(222, 4, 4));
        gestRes.setColorTextHover(new java.awt.Color(255, 0, 0));
        gestRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestResActionPerformed(evt);
            }
        });

        vigHouse.setBackground(new java.awt.Color(255, 0, 0));
        vigHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/recurso/home.png"))); // NOI18N
        vigHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vigHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vigHouseMouseClicked(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/recurso/back.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DesplegableLayout = new javax.swing.GroupLayout(Desplegable);
        Desplegable.setLayout(DesplegableLayout);
        DesplegableLayout.setHorizontalGroup(
            DesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesplegableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(80, 80, 80)
                .addComponent(vigHouse)
                .addContainerGap())
            .addComponent(gestRes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesplegableLayout.setVerticalGroup(
            DesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesplegableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vigHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(gestRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PeneContentLayout = new javax.swing.GroupLayout(PeneContent);
        PeneContent.setLayout(PeneContentLayout);
        PeneContentLayout.setHorizontalGroup(
            PeneContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeneContentLayout.createSequentialGroup()
                .addComponent(Desplegable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar))
        );
        PeneContentLayout.setVerticalGroup(
            PeneContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desplegable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PeneContentLayout.createSequentialGroup()
                .addGroup(PeneContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeneContentLayout.createSequentialGroup()
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeneContentLayout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(PrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PeneContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PeneContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
        System.exit(0);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarMouseClicked

    private void modDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modDataActionPerformed

        new CambiaPanel(PrincipalPane, new modDataPane(cod()));
    }//GEN-LAST:event_modDataActionPerformed

    private void gestResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestResActionPerformed

        new CambiaPanel(PrincipalPane, new gestReservasPane());
    }//GEN-LAST:event_gestResActionPerformed

    private void vigHouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vigHouseMouseClicked
        new CambiaPanel(PrincipalPane, new usuarioHome(cod()));
    }//GEN-LAST:event_vigHouseMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        login Login = new login();
        Login.setVisible(true);
        dispose();
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desplegable;
    private javax.swing.JPanel PeneContent;
    private javax.swing.JPanel PrincipalPane;
    private javax.swing.JLabel back;
    private javax.swing.JLabel cerrar;
    private Vista.recurso.RSButtonMetro gestRes;
    private Vista.recurso.RSButtonMetro modData;
    private javax.swing.JLabel vigHouse;
    // End of variables declaration//GEN-END:variables
}
