/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.admin;

import Logica.usuarioLogica;
import Modelo.Usuario;
import Vista.CambiaPanel;
import Vista.login;
import Vista.usuarioHome;
import Vista.usuarioHome;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ander
 */
public class admPrincipal extends javax.swing.JFrame {

    private usuarioLogica usuarioLogica = new usuarioLogica();
    Usuario usuarioConsulta;
    int codUsuario;
    public admPrincipal(int codUsuario) {
        this.codUsuario = codUsuario;
        initComponents();
        this.setResizable(false);
        
        this.setLocationRelativeTo(null);
       this.gstAdmi.setSelected(true);
       new CambiaPanel(PrincipalPane, new usuarioHome(codUsuario));
    }
    
    public int cod(){
        return codUsuario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PeneContent = new javax.swing.JPanel();
        PrincipalPane = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        Desplegable = new javax.swing.JPanel();
        gstProg = new Vista.recurso.RSButtonMetro();
        gstAdmi = new Vista.recurso.RSButtonMetro();
        gstAsign = new Vista.recurso.RSButtonMetro();
        gsdAmb = new Vista.recurso.RSButtonMetro();
        gstSede = new Vista.recurso.RSButtonMetro();
        admHouse = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PeneContent.setBackground(new java.awt.Color(255, 255, 255));
        PeneContent.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        PrincipalPane.setBackground(new java.awt.Color(255, 255, 255));
        PrincipalPane.setPreferredSize(new java.awt.Dimension(628, 406));
        PrincipalPane.setLayout(new javax.swing.BoxLayout(PrincipalPane, javax.swing.BoxLayout.LINE_AXIS));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(230, 0, 0));
        cerrar.setText(" X ");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        Desplegable.setBackground(new java.awt.Color(255, 0, 0));

        gstProg.setText("Gestionar Programa");
        gstProg.setColorHover(new java.awt.Color(255, 255, 255));
        gstProg.setColorNormal(new java.awt.Color(255, 0, 0));
        gstProg.setColorPressed(new java.awt.Color(222, 4, 4));
        gstProg.setColorTextHover(new java.awt.Color(255, 0, 0));
        gstProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstProgActionPerformed(evt);
            }
        });

        gstAdmi.setText("Gestionar Usuarios");
        gstAdmi.setColorHover(new java.awt.Color(255, 255, 255));
        gstAdmi.setColorNormal(new java.awt.Color(255, 0, 0));
        gstAdmi.setColorPressed(new java.awt.Color(222, 4, 4));
        gstAdmi.setColorTextHover(new java.awt.Color(255, 0, 0));
        gstAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstAdmiActionPerformed(evt);
            }
        });

        gstAsign.setText("Gestionar Asignatura");
        gstAsign.setColorHover(new java.awt.Color(255, 255, 255));
        gstAsign.setColorNormal(new java.awt.Color(255, 0, 0));
        gstAsign.setColorPressed(new java.awt.Color(222, 4, 4));
        gstAsign.setColorTextHover(new java.awt.Color(255, 0, 0));
        gstAsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstAsignActionPerformed(evt);
            }
        });

        gsdAmb.setText("Gestionar Ambiente");
        gsdAmb.setColorHover(new java.awt.Color(255, 255, 255));
        gsdAmb.setColorNormal(new java.awt.Color(255, 0, 0));
        gsdAmb.setColorPressed(new java.awt.Color(222, 4, 4));
        gsdAmb.setColorTextHover(new java.awt.Color(255, 0, 0));
        gsdAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsdAmbActionPerformed(evt);
            }
        });

        gstSede.setText("Gestionar Sede");
        gstSede.setColorHover(new java.awt.Color(255, 255, 255));
        gstSede.setColorNormal(new java.awt.Color(255, 0, 0));
        gstSede.setColorPressed(new java.awt.Color(222, 4, 4));
        gstSede.setColorTextHover(new java.awt.Color(255, 0, 0));
        gstSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstSedeActionPerformed(evt);
            }
        });

        admHouse.setBackground(new java.awt.Color(255, 0, 0));
        admHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/recurso/home.png"))); // NOI18N
        admHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admHouseMouseClicked(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/recurso/back.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DesplegableLayout = new javax.swing.GroupLayout(Desplegable);
        Desplegable.setLayout(DesplegableLayout);
        DesplegableLayout.setHorizontalGroup(
            DesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gstAsign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gstProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gsdAmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gstSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesplegableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(80, 80, 80)
                .addComponent(admHouse)
                .addContainerGap())
            .addComponent(gstAdmi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesplegableLayout.setVerticalGroup(
            DesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesplegableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(gstAdmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gstAsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gstProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gsdAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gstSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PeneContentLayout = new javax.swing.GroupLayout(PeneContent);
        PeneContent.setLayout(PeneContentLayout);
        PeneContentLayout.setHorizontalGroup(
            PeneContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeneContentLayout.createSequentialGroup()
                .addComponent(Desplegable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PeneContentLayout.setVerticalGroup(
            PeneContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desplegable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PeneContentLayout.createSequentialGroup()
                .addGroup(PeneContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeneContentLayout.createSequentialGroup()
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeneContentLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(PrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PeneContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PeneContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
        System.exit(0);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarMouseClicked
    
    
    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        login Login = new login();
        Login.setVisible(true);
        dispose();
        this.setVisible(false);
        
    }//GEN-LAST:event_backMouseClicked

    private void gstAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstAdmiActionPerformed
        
        new CambiaPanel(PrincipalPane, new gstUsuarios());
        
    }//GEN-LAST:event_gstAdmiActionPerformed

    private void admHouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admHouseMouseClicked
      new CambiaPanel(PrincipalPane, new usuarioHome(cod()));
    }//GEN-LAST:event_admHouseMouseClicked

    private void gstAsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstAsignActionPerformed
        new CambiaPanel(PrincipalPane, new gstAsignPane());
    }//GEN-LAST:event_gstAsignActionPerformed

    private void gstProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstProgActionPerformed
        new CambiaPanel(PrincipalPane, new gstProgPane());
    }//GEN-LAST:event_gstProgActionPerformed

    private void gsdAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsdAmbActionPerformed
       new CambiaPanel(PrincipalPane, new gstAmbPane());
    }//GEN-LAST:event_gsdAmbActionPerformed

    private void gstSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstSedeActionPerformed
        new CambiaPanel(PrincipalPane, new gstSedePane());
    }//GEN-LAST:event_gstSedeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desplegable;
    private javax.swing.JPanel PeneContent;
    private javax.swing.JPanel PrincipalPane;
    private javax.swing.JLabel admHouse;
    private javax.swing.JLabel back;
    private javax.swing.JLabel cerrar;
    private Vista.recurso.RSButtonMetro gsdAmb;
    private Vista.recurso.RSButtonMetro gstAdmi;
    private Vista.recurso.RSButtonMetro gstAsign;
    private Vista.recurso.RSButtonMetro gstProg;
    private Vista.recurso.RSButtonMetro gstSede;
    // End of variables declaration//GEN-END:variables
}
